<?php

//* ESTE DOCUMENTO RECIBE PETICIONES QUE VIENEN DE AFUERA

require_once ".autoloader";


extract($_REQUEST);                    //* ESTO EXTRAE LAS PETICIONES DE LOS USUARIOS
// print_r("<pre>");
// print_r($_REQUEST);

//* LOS DATOS QUE EXTRAIDO DE LOS USUARIOS EN LA URL SE CONVIERTEN EN DATOS LOS CUALES PUEDO CONSULTAR DENTRO DE LA VARIABLE ACTION, QUE ES DONDE
//* SE ALMACENA ESA INFORMACION

// print_r($action);
// print_r("<br>");
// print_r($otro);


//* ISSET ES UNA FUNCION QUE VALIDA SI DENTRO DE LA FUNCION VIENE CON ALGUN VALOR. DE ESTA FORMA PODEMOS DAR INSTRUCCIONES SI VIENE O NO.


